version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: maquina
      POSTGRES_DB: template
      POSTGRES_PASSWORD: maquina-
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    container_name: template
    depends_on:
      - db
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/srv/app
    environment:
      NODE_ENV: development
      DB_USER: maquina
      DB_PASSWORD: maquina-
      DB_NAME: template
      DB_HOST: db
